### PR TITLE
Add sequencer orderings (FIFO, LIFO, HighestValue, Random)

### LINKED ISSUE #58: Change the sequencer ordering
The current implementation does fee sorting, so transactions with higher fee go first in the batch. Change the way the ordering is done, you might consider:

- First In, First Out (FIFO)
- Last In, First Out (LIFO)
- Highest value transaction first
- Random ordering

You have any questions or problems you can always join our [Discord](https://discord.gg/eaVKXPmtWk) and ask :+]

### PR DESCRIPTION
**Pull request by fewwwww**
Closes #58

### CODE REVIEW

**Review by mateuszradomski — CHANGES_REQUESTED** [review]
Hi,

The code looks good and you've provided tests so that's an easy approve for me. But I'd also like to see the ability to choose between sequencer orderings. You can add a new configuration field in the objects returned by `getConfig` calls - both for local and production. This field can be by default "FEE" if no env variable is provided otherwise it's going to be extracted from `BYOR_SEQUENCER_ORDERING`. Propagate this configuration to `BatchPoster` and call the correct `popN` function. 

If you'll have any problems, shoot :))

**Comment by fewwwww** [comment]
Thanks for the detailed guide! I have added the configuration to choose between sequencer orderings.

**Review by mateuszradomski — APPROVED** [review]
Looks great, GJ!

**Comment by fewwwww** [comment]
Thanks! The last GitHub Actions failed due to the code formatting. I've submitted a new commit, and this need you to approve the new GitHub Actions for merging.

**Pull request merged**
